### ISSUE TITLE
Not really an issue,but I'm confused on the README guide. 

### ISSUE THREAD

**Issue by Average-Anon** [Amenly/LoyalFans#2]
The "In the command line, run the following:",I assumed it meant the vanilla cmd and I tried it. Didn't work.
Then I figured that since it mentioned Python,it's probably the Python's cmd so I downloaded it and tried it on the python cmd. Didn't work.
I tried using Powershell on the file destination. Didn't work either. 
I'm fairly new to python so I don't know what my mistake is. I hope this can be resolved or the README gets updated with more information.

**Comment by Amenly** [comment]
What does it say when you run those commands? Are you having this issue when trying to install the dependencies inside the `requirements.txt` file or when trying to run the `loyalfans.py` script?

Please copy and paste the entire error message. Also, run `python --version` in the command line and tell me which version of Python you're using.

**Comment by Average-Anon** [comment]
Well,first I tried to run the 'pip install -r requirements.txt'. 

When I used default windows command: 
'pip' is not recognized as an internal or external command,
operable program or batch file.

When I used python command box:
  File "<stdin>", line 1
    pip install -r requirements.txt
        ^
SyntaxError: invalid syntax

I tried to run python --version but:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined

I downloaded the python 3.90 version.

**Comment by Amenly** [comment]
This has something to do with the way you installed Python. Maybe [this link](https://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command) can help you. If not, you should either try searching `pip is not recognized python` *or* consider uninstalling Python and looking up a tutorial on YouTube on how to install Python on Windows (Corey Schafer might have something).
