### ISSUE TITLE
The scraping isn't really effective.

### ISSUE THREAD

**Issue by Average-Anon** [Amenly/LoyalFans#3]
Tried it out and it works. However,only some of the pictures and videos was downloaded properly. Most of the videos and pictures are empty files. 

This can be fixed by deleting the empty files and running the program again,but that only fixes some of the files and leave some still empty. I rinsed and repeat several times (maybe 15-20 times) until every pictures and videos properly downloaded. I guess it works but needs to be improved to make sure each files can be downloaded properly the first time it runs. 

This could be a problem only on my part but hopefully it can be solved or improved.

**Comment by Amenly** [comment]
I just ran the script on a Windows machine and could not replicate any of the issues you're describing.

I need the following information from you:
* Which Python version are you using?
* Which version of the script are you using?
* Open the `config.json` file and copy and paste your options under `"settings"`

**Comment by Average-Anon** [comment]
- I'm using Python 3.9.0

- Version 1.3.0

- `"destination_path": "",
            "separate_file_types": true,
            "download_preview_videos": true,
            "avoid_duplicates": true,
            "use_original_dates": true
        },
        "urls": {
            "profile_url": "https://www.loyalfans.com/api/v2/profile/star/{}/",
            "timeline_url": "https://www.loyalfans.com/api/v2/social/timeline/{}?limit={}&page=0/",
            "messages_url": "https://www.loyalfans.com/api/v1/messages/with/{}"
        }
    }
}
`

**Comment by Amenly** [comment]
Try using the latest version (1.4.0) and tell me if you're still experiencing the same issue. You might have to rerun `pip install -r requirements.txt` again.

**Comment by Average-Anon** [comment]
Tried the latest version. It is improving. The ones properly downloading is more than the ones that's empty. But there are still empty files. I'm not sure if it's my internet that's causing this. My internet speed is like,0.5 mbps so maybe that's the issue. But it's definitely an improvement. 

Question: How do I configure for other creator? Do I have to make a new .json file? New separate script? Add more lines to the .json files?

**Comment by Amenly** [comment]
Hmm, well, I can't really do anything to help you with that. I had thought that maybe the issue was due to the operating system but it works fine on my Windows machine. 

What do you mean by "configure for other creator"? As long as you enter valid values for the authorization cookie and the user agent, the same .json file will work for any creator that you're following/subscribed to. Version 1.4.0 will tell you if you need to update those values.

**Comment by Average-Anon** [comment]
Thanks for that. Looking forward for more.
