### ISSUE TITLE
timezone fix

### ISSUE THREAD

**Issue by excludedBittern8** [Amenly/LoyalFans#5]
Not 100 percent sure what this function is for, but their seems to be an error with timezones
 my timezone at timezone = time.strftime('%z', time.gmtime()) is actually +0000, which messes up the line: delta = datetime.timedelta(hours=int(timezone))

Because basically your left with just +, which crashes the program

to fix this I just added

timezone=timezone.replace('+', '')

full function
```
`iso_datetime = parse(date)
    timezone = time.strftime('%z', time.gmtime())
    timezone=timezone.replace('+', '')
    
  if timezone == '0000':
        timezone = 0
  
  else:
        timezone = timezone.replace('0', '')
   delta = datetime.timedelta(hours=int(timezone))
   timestamp = datetime.datetime.timestamp(iso_datetime + delta)
   return timestamp`
```

**Comment by Amenly** [comment]
Ah, I had a feeling there would be an issue with this. For some reason, I hadn't thought GMT would appear as `+0000`; I thought it would only be `0000` but now that seems silly.

This function is intended to set the dates for any downloaded files. I have another update for the script coming soon so I think I'll just get rid of this part and use the unix timestamps that LoyalFans provides. In the meantime, I'll update the current script.
